### PR TITLE
tests: run softhsm-using tests in serial with each other

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by mheese** [comment]
this probably totally makes sense. I want to look at that "serial" crate first though.

@mathstuf thanks though, it's totally appreciated! :)

**Comment by mathstuf** [comment]
Might be worth marking them with `#[serial(softhsm)]` so that they're not excluding other serial-but-not-using-SoftHSM tests.

**Comment by mathstuf** [comment]
Ping?

**Comment by mheese** [comment]
@mathstuf I apologize, I thought I merged this a long time ago

**Pull request merged**
